/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codeWarsJava;

import java.lang.reflect.Array;

public class App {

    //To test anything, just uncomment it. for 'average' just uncomment the code block below on this page.
    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());  //returns Hello World.
//        average();
//        System.out.println(BitCounting.countBits(1234));  //should return 10011010010.
//        System.out.println(BraceChecker.isValid("[]"));  //true
//        System.out.println(BraceChecker.isValid("[(])"));  //false
//        System.out.println(BraceChecker.isValid("([{}])"));  //true
//        System.out.println(BraceChecker.isValid("[({})](]"));  //false
//        CompoundInterest.checker();
//        System.out.println(JadenCase.toJadenCase("Hi, my name is jared."));  //returns Hi, My Name Is Jared.
//        MultiDimensionArray.make();  //returns columns and rows with values.
//    	  Numbers20.result();  //returns nums 1-20 with certain nums replaced with words.
//    	System.out.println(SquareDigit.squareDigits(9119));   //works great.
//    	int[] intArray = {5,1,3,4,1}; //Uncomment this if you uncomment line below.
//    	int[] intArray2 = {1,1,1,3,1}; //Uncomment this if you uncomment line below.
//    	System.out.println(Greed.greedy(intArray)); //Should return 250
//    	System.out.println(Greed.greedy(intArray2)); //Should return 1100
//    	StringSplit.splitter();  //I think it works. Check again.
//    	System.out.println(ToCamelCase.toCamelCase("the_Stealth_Warrior"));  //Doesn't work yet...
//    	System.out.println(SillyAddition.add(248, 208));
//    	System.out.println(SillyAddition.add(36, 245));
//    	System.out.println(DigitalRoot.digital_root(16));
//    	System.out.println(DigitalRoot.digital_root(942));
//        System.out.println(SqInRect2.sqInRect(5, 3));  //Answer should be [3, 2, 1, 1]
//        System.out.println(SqInRect2.sqInRect(17, 30));  //Answer should be [17, 13, 4, 4, 4, 1, 1, 1, 1,]
//        System.out.println(CamelCaseWithSpace.camelCase("camelcasing"));
//        System.out.println(CamelCaseWithSpace.camelCase("camelCasing"));
//        System.out.println(CountDigits.countDigits(43214));
//        System.out.println(LongestPalindrome.longestPalindrome("a"));
//        System.out.println(LongestPalindrome.longestPalindrome("aa"));
//        String[] strarr = {"tree", "foling", "trashy", "blue", "abcdef", "uvwxyz"};
//        System.out.println(ConsecutiveStrings.longestConsec(strarr, 2));
//        System.out.println(ConsecutiveStrings.longestConsec(new String[] {"zone", "abigail", "theta", "form", "libe", "zas", "theta", "abigail"}, 2));
//        System.out.println(SumOfParts.sumParts(new int[] {})); //{0}
//        System.out.println(SumOfParts.sumParts(new int[] {0, 1, 3, 6, 10}));  //new int[] {20, 20, 19, 16, 10, 0}
//        System.out.println(SumOfParts.sumParts(new int[] {1, 2, 3, 4, 5, 6})); //new int[] {21, 20, 18, 15, 11, 6, 0}
//        System.out.println(SumOfParts.sumParts(new int[] {744125, 935, 407, 454, 430, 90, 144, 6710213, 889, 810, 2579358})); //{10037855, 9293730, 9292795, 9292388, 9291934, 9291504, 9291414, 9291270, 2581057, 2580168, 2579358, 0}
//        long[][] lst = new long[][] { {1, 2}, {1, 3}, {10, 40} };
//        long[][] lst2 = new long[][] { {69, 130}, {87, 1310}, {30, 40} };
//        System.out.println(Fracts.convertFrac(lst2)); //(18078,34060)(2262,34060)(25545,34060)
//        System.out.println(Fracts.convertFrac(lst)); //(6,12)(4,12)(3,12)
        /*Note: This is saved as an example to show how to use non-static methods and share variables.
        SqInRect sir = new SqInRect(); 
        sir.sqInRect(5, 3);   //look above for answer.
        sir.sqInRect(17, 30);  //look above for answer.
        */

    }
    
/*    private static void average() {
    	System.out.println("enter 5 numbers:");
		final Scanner input = new Scanner(System.in);
		int total = 0;
		int grade;
		int average;
		int counter = 0;
	

		while (counter < 5) {
			grade = input.nextInt();
			total += grade;
			counter++;
		}
		input.close();
		average = total/5; 
		System.out.println("Your average is: " + average);
	}
*/
//In mathematics Average is the sum divided by the count
 
}
